version: '3.8'

services:
  # Frontend service (built with Nginx serving static files)
  frontend:
    image: ghcr.io/libradley/anti-timesink/frontend:latest@sha256:a8c06e7b5d86608e5d0922c3495c9e03cbbdec9bed3eb0c90ff178979f7b3e1f
    container_name: frontend
    ports:
      - "80:80"  # Expose frontend on port 80 (accessible externally)
    networks:
      - frontend-backend-net
    depends_on:
      - backend  # Make sure backend is up before starting frontend

  # Backend service (Python app, could be Flask/Django, etc.)
  backend:
    image: ghcr.io/libradley/anti-timesink/backend:latest@sha256:3924917134e014f2ae89a6c19bf231a8d64163f6950d6195eaaf50df35f6faeb
    container_name: backend
    ports:
      - "5000:5000"  # Expose backend on port 5000 (accessible externally)
    networks:
      - frontend-backend-net
    environment:
      - BACKEND_URL=http://backend:5000  # Reference the backend service by name

  # Dnsmasq service (providing DNS and blocking services)
  dnsmasq:
    image: ghcr.io/libradley/anti-timesink/dnsmasq:latest@sha256:6065c2bbc24943e43e8a61c23d0dd453621ae53caa95ca0ff84cc188d271436a
    container_name: dnsmasq
    ports:
      - "53:53/udp"   # Expose DNS port
      - "53:53/tcp"   # Expose DNS port
    networks:
      - frontend-backend-net


networks:
  frontend-backend-net:
    driver: bridge  # This allows communication between containers in the same network